import type { InventoryItem } from "./inventory.ts";

export const initialInventory: InventoryItem[] = [
  {
    id: 1,
    itemCode: "ITM-001",
    itemName: "Laptop Dell XPS",
    category: "Electronics",
    stockQuantity: 25,
    unitPrice: 85000,
    warehouse: "Chennai Warehouse",
    status: "In Stock",
  },
  {
    id: 2,
    itemCode: "ITM-002",
    itemName: "Wireless Mouse",
    category: "Accessories",
    stockQuantity: 8,
    unitPrice: 1200,
    warehouse: "Coimbatore Warehouse",
    status: "Low Stock",
  },
  {
    id: 3,
    itemCode: "ITM-003",
    itemName: "Office Chair",
    category: "Furniture",
    stockQuantity: 0,
    unitPrice: 7500,
    warehouse: "Bangalore Warehouse",
    status: "Out of Stock",
  },
  {
    id: 4,
    itemCode: "ITM-004",
    itemName: "Keyboard",
    category: "Accessories",
    stockQuantity: 45,
    unitPrice: 2500,
    warehouse: "Chennai Warehouse",
    status: "In Stock",
  },
  {
    id: 5,
    itemCode: "ITM-005",
    itemName: "Monitor 24 Inch",
    category: "Electronics",
    stockQuantity: 5,
    unitPrice: 18000,
    warehouse: "Coimbatore Warehouse",
    status: "Low Stock",
  },
];